# application.yml
spring:
  redis:
    port: 6379
    host: localhost
    database: 2
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
    stream:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/notify_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
  mail:
    username: choerodon
    password: choerodon
    protocol: smtp
    host: smtp.qiye.aliyun.com
    port: 465
    properties:
      mail.smtp.ssl.enable: true
      mail.send.name: choerodon
    test-connection: false
  freemarker:
    check-template-location: false
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  stream:
    queue:
      enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
file-service:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
choerodon:
  schedule:
    consumer:
      enabled: true # 启用任务调度消费端
      thread-num: 3 # 任务调度消费线程数
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
  notify:
    init-spring-email-config: true # 是否根据spring.mail的配置初始化email配置
  ws:
    paths: /choerodon:msg/**
    oauth: false
    heart-beat-interval-ms: 10000
  eureka:
    event:
      max-cache-size: 300 # 存储的最大失败数量
      retry-time: 5 # 自动重试次数
      retry-interval: 3 # 自动重试间隔(秒)
      skip-services: "**register-server", "**gateway**", "zipkin**", "hystrix**", "oauth**", "config**"
logging:
  level:
    javax.mail: info
    io.choerodon.notify.service.impl.PmSendTask: info

