# application.yml
spring:
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
    stream:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/notify_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  kafka: #使用原生spring kafka需要配置
    bootstrap-servers: localhost:9092
    consumer:
      group-id: iam-service
      auto-offset-reset: earliest
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  stream:
    queue:
      enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
file-service:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
choerodon:
  notify:
    init-email-config: true # 是否根据spring.mail的配置初始化email配置
    business-type:
      验证码: 用于获取验证码，验证用户信息
      用户绑定: 绑定邮箱、手机号的反馈信息
      用户激活: 首次注册，确认用户注册成功
      获取密码: 忘记密码后，根据用户操作提供用户名及相应密码
      密码修改: 反馈用户密码修改成功
      添加成员: 项目添加新成员时，及时反馈给被添加的用户
      用户角色变更: 通知用户的角色权限发生变化
    email:
      account: fly_left@126.com
      password: 123654789Zj
      protocol: smtp
      send-name: choerodon
      host: smtp.126.com
      port: 25
      ssl: false
