# application.yml
spring:
  redis:
    port: 6379
    host: localhost
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
    stream:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/notify_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  kafka: #使用原生spring kafka需要配置
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: notify-service
      auto-offset-reset: latest
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
  mail:
    username: choerodon
    password: choerodon
    protocol: smtp
    host: smtp.qiye.aliyun.com
    port: 465
    properties:
      mail.smtp.ssl.enable: true
      mail.send.name: choerodon
    test-connection: false
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  stream:
    queue:
      enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
file-service:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
choerodon:
  notify:
    init-spring-email-config: true # 是否根据spring.mail的配置初始化email配置
    skip-services: register-server, api-gateway, gateway-helper, oauth-server, config-server, event-store-service
    fetch-time: 5
  ws:
    paths: /choerodon_msg/**
    oauth: false
logging:
  level:
   javax.mail: info
