# application.yml
spring:
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
    stream:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/notify_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  kafka: #使用原生spring kafka需要配置
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: notify-service
      auto-offset-reset: latest
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
  mail:
    username: choerodon
    password: choerodon
    protocol: smtp
    host: smtp.qiye.aliyun.com
    port: 465
    properties:
      mail.smtp.ssl.enable: true
      mail.send.name: choerodon
    test-connection: false
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  stream:
    queue:
      enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
file-service:
  ribbon:
    ReadTimeout: 15000
    ConnectTimeout: 15000
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
choerodon:
  notify:
    types:
      forgetPassword:
        name: 忘记密码
        description: 用户触发忘记密码，发送验证邮件。(LDAP用户不允许重置密码)
      addUser:
        name: 添加/导入新用户
        description: 管理员添加或导入新用户时，新用户收到自己的账户信息
      addFunction:
        name: 添加新功能
        description: 系统添加新功能时，给用户发送新功能的介绍和操作指南
      modifyPassword:
        name: 修改密码
        description: 用户在平台修改密码后反馈密码修改成功的通知，确认是否是用户的操作
      modifyMoemberRole:
        name: 用户角色变更
        description: 通知用户的角色权限发生变化
        level: organization
    init-spring-email-config: true # 是否根据spring.mail的配置初始化email配置
    skip-services: register-server, api-gateway, gateway-helper, oauth-server, config-server, event-store-service
    fetch-time: 5
    is-local: false
logging:
  level:
   javax.mail: info
